//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Linq;

namespace PracticaEscuela.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Inscripciones = new HashSet<Inscripciones>();
        }
    
        public int Id { get; set; }
        public int CursoId { get; set; }
        public string Division { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripciones> Inscripciones { get; set; }

        public void Save(Curso curso)
        {
            using (EscuelaEntities db = new EscuelaEntities())
            {
                db.Curso.Add(curso);
                db.SaveChanges();
            }
        }

        public ICollection<Curso> Get()
        {
            using (EscuelaEntities db = new EscuelaEntities())
            {
                return db.Curso.ToList();
            }
        }
    }
}
