//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaEscuela.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripciones
    {
        public int Id { get; set; }
        public int CursoId { get; set; }
        public int AlumnoId { get; set; }
        public bool Activo { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Curso Curso { get; set; }
    }
}
